### PR TITLE
table: fix rebalancing of long merged columns, fixes #350

### LINKED ISSUE #350: Bug: a size of columns with merged cells is not calculated correctly
Hello! Thank you for your work on this useful package!

**Describe the bug**
When calculating the size of columns, merging table cells is not taken into account

**To Reproduce**
[Go Playground.](https://go.dev/play/p/Bfe_lFUtf-T)

```
package main

import (
	"fmt"
	"github.com/jedib0t/go-pretty/v6/table"
	"github.com/jedib0t/go-pretty/v6/text"
)

func main() {
	tw := table.NewWriter()
	tw.AppendHeader(table.Row{"ID", "Date", "From", "To", "Subject", "Size"})
	tw.AppendRow(table.Row{
		4,
		"2024-11-18T09:30:54Z",
		"Shaylee McDermott",
		"",
		"Tote bag photo booth lumbersexual normcore synth meh lumbersexual disrupt craft beer aesthetic.",
		"4.2 MB",
	})
	tw.AppendRow(table.Row{
		4,
		"2024-11-18T09:30:54Z",
		"Anahi Braun ",
		"",
		"Mumblecore salvia mumblecore austin tofu viral asymmetrical small batch distillery you probably haven't heard of them.",
		"4.2 MB",
	})
	tw.AppendRow(table.Row{
		4,
		"2024-11-18T09:30:54Z",
		"Brando Barton",
		"",
		"Before they sold out jean shorts chartreuse neutra fixie flexitarian goth art party small batch sriracha.",
		"4.2 MB",
	})
	const ID = "AAMkADdiOWM1OTBkLTBhZjEtNGFiNS1hOGYwLTY2YWFmOGQyNTMxNgBGAAAAAADBju3TxrP2SZIsqjNb8hmoBwA9J0gY/4/nQ73Lmp9F9NoaAABlJ281AAA9J0gY/4/nQ73Lmp9F9NoaAABlJ6bLAAA="
	tw.AppendRow(
		table.Row{ID, ID, ID, ID, ID, ID},
		table.RowConfig{
			AutoMerge:      true,
			AutoMergeAlign: text.AlignLeft,
		})
	fmt.Println(tw.Render())
}
```

**Expected behavior**
```
	+----+----------------------+-------------------+----+------------------------------------------------------------------------------------------------------------------------+--------+
	| ID | DATE                 | FROM              | TO | SUBJECT                                                                                                                | SIZE   |
	+----+----------------------+-------------------+----+------------------------------------------------------------------------------------------------------------------------+--------+
	|  4 | 2024-11-18T09:30:54Z | Shaylee McDermott |    | Tote bag photo booth lumbersexual normcore synth meh lumbersexual disrupt craft beer aesthetic.                        | 4.2 MB |
	|  4 | 2024-11-18T09:30:54Z | Anahi Braun       |    | Mumblecore salvia mumblecore austin tofu viral asymmetrical small batch distillery you probably haven't heard of them. | 4.2 MB |
	|  4 | 2024-11-18T09:30:54Z | Brando Barton     |    | Before they sold out jean shorts chartreuse neutra fixie flexitarian goth art party small batch sriracha.              | 4.2 MB |
	|  AAMkADdiOWM1OTBkLTBhZjEtNGFiNS1hOGYwLTY2YWFmOGQyNTMxNgBGAAAAAADBju3TxrP2SZIsqjNb8hmoBwA9J0gY/4/nQ73Lmp9F9NoaAABlJ281AAA9J0gY/4/nQ73Lmp9F9NoaAABlJ6bLAAA=                            |
	+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
	
```

**Actual behavior**

```
	+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
	| ID                                                                                                                                                       | DATE                                                                                                                                                     | FROM                                                                                                                                                     | TO                                                                                                                                                       | SUBJECT                                                                                                                                                  | SIZE                                                                                                                                                     |
	+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
	| 4                                                                                                                                                        | 2024-11-18T09:30:54Z                                                                                                                                     | Shaylee McDermott                                                                                                                                        |                                                                                                                                                          | Tote bag photo booth lumbersexual normcore synth meh lumbersexual disrupt craft beer aesthetic.                                                          | 4.2 MB                                                                                                                                                   |
	| 4                                                                                                                                                        | 2024-11-18T09:30:54Z                                                                                                                                     | Anahi Braun                                                                                                                                              |                                                                                                                                                          | Mumblecore salvia mumblecore austin tofu viral asymmetrical small batch distillery you probably haven't heard of them.                                   | 4.2 MB                                                                                                                                                   |
	| 4                                                                                                                                                        | 2024-11-18T09:30:54Z                                                                                                                                     | Brando Barton                                                                                                                                            |                                                                                                                                                          | Before they sold out jean shorts chartreuse neutra fixie flexitarian goth art party small batch sriracha.                                                | 4.2 MB                                                                                                                                                   |
	| AAMkADdiOWM1OTBkLTBhZjEtNGFiNS1hOGYwLTY2YWFmOGQyNTMxNgBGAAAAAADBju3TxrP2SZIsqjNb8hmoBwA9J0gY/4/nQ73Lmp9F9NoaAABlJ281AAA9J0gY/4/nQ73Lmp9F9NoaAABlJ6bLAAA=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
	+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

	
```

**Software:**
 - GoLang Version 1.23

### PR DESCRIPTION
**Pull request by knrc**
Firstly, thanks very much for making this code available as it proved to be very useful for one of my projects.  By way of a thank you I took a look at #350 and believe I have a solution for rebalancing the space from the merged cells.  Please take a look. There may be some edge cases I have not considered, if you can think of any please let me know and I can rework the changes.

## Proposed Changes
  - separate merged cell information from maximum column width calculation
  - calculate horizontal merged cell widths after header, body, foot complete
  - padding applied to smaller cells

Fixes #350.

### CODE REVIEW

File: table/render_automerge_test.go [hunk 1]
```diff
@@ -413,20 +413,20 @@ func TestTable_Render_AutoMerge(t *testing.T) {
...
+│   │          │          │          │          │  D133792CCFA501FD8DA53EE3  │  D133792CCFA501FD8DA53EE3  │
+│   │          │          │          │          │  68FED20E5FE0248C3A0B64F9  │  68FED20E5FE0248C3A0B64F9  │
+│   │          │          │          │          │  8A6533CEE1DA614C3A8DDEC7  │  8A6533CEE1DA614C3A8DDEC7  │
+│   │          │          │          │          │  91FF05FEE6D971D57C134832  │  91FF05FEE6D971D57C134832  │
+│   │          │          │          │          │          0F4EB42DR         │         0F4EB42DRR         │
+├───┼──────────┼──────────┼──────────┼──────────┼────────────────────────────┴────────────────────────────┤
+│ 2 │ a.a.a.a  │ Pod 1A   │ NS 1A    │ C 2      │                            Y                            │
+├───┼──────────┼──────────┼──────────┼──────────┼─────────────────────────────────────────────────────────┤
+│ 3 │ a.a.a.a  │ Pod 1A   │ NS 1A    │ C 2      │                            Y                            │
+└───┴──────────┴──────────┴──────────┴──────────┴─────────────────────────────────────────────────────────┘`)
```
Comment (jedib0t) [inline table/render_automerge_test.go:429]: It looks like there might be a tiny bug with centering, or measuring the max length. In Row 1, merged Column 5/6 and merged Column 7/8 contents can be shrunk down further by 2 spaces (1 on each side).

**Review by jedib0t — CHANGES_REQUESTED** [review]
I appreciate the compliments. Started out as my first "learn-golang" project, and I needed a table writer library with more control over the styles and sorting. 👍🏽 

As to this PR, this is awesome. Thanks for fixing this bug. Before I merge it, can you take a look to see if the one comment below is a genuine bug and if it can be fixed?

File: table/render_automerge_test.go (hunk 1 above)
Comment (knrc) [reply table/render_automerge_test.go:429]: I can take a look at the details later this evening, will let you know what I find out.

Comment (jedib0t) [reply table/render_automerge_test.go:429]: Thanks! Not a deal breaker, but we may as well try while this code is fresh in our minds.

Comment (knrc) [reply table/render_automerge_test.go:429]: It's a slight difference in implementation, the previous code was rounding down the mergedColumnLength when dividing by the numMergedColumns

https://github.com/jedib0t/go-pretty/blob/bfe1b7ccedef3e135fcffb34f9888172d0cd992b/table/render_init.go#L82

In this instance mergedColumnLength was 23, numMergedColums 2 and maxLengthSplitAcrossColumns was therefore 11 (22 instead of 23, missing one space).

The new code keeps track of the remaining space by subtracting each time, so is still padding out to 23 spaces length.

**Review by jedib0t — APPROVED** [review]

**Comment by jedib0t** [comment]
Thanks for the bug-fix @knrc !
