### PR TITLE
text: Wrap* should account for display width; fixes #344

### LINKED ISSUE #344: There is an issue with calculating the length of line breaks in wrap func
**Describe the bug**
code:
```golang
func TestRenderEndpointTable(tt *testing.T) {

	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.SetStyle(table.StyleLight)
	t.AppendHeader(table.Row{"idx", "A", "B", "C"})

	t.AppendRows([]table.Row{
		{1, text.WrapSoft("abcd甲乙丙丁abcd", 10), text.WrapHard("abcd甲乙丙丁abcd", 10), text.WrapText("abcd甲乙丙丁abcd", 10)},
		{2, text.WrapSoft("abcdabcdabcdabcdabcdabcd", 10), text.WrapHard("abcdabcdabcdabcdabcdabcd", 10), text.WrapText("abcdabcdabcdabcdabcdabcd", 10)},
		{3, text.WrapSoft("甲乙丙丁甲乙丙丁甲乙丙丁", 10), text.WrapHard("甲乙丙丁甲乙丙丁甲乙丙丁", 10), text.WrapText("甲乙丙丁", 10)},
	})

	t.Render()
}
```

render:

image

There is clearly still space in columns A and B of the first and second rows, but it has wrapped

**Expected behavior**

in columns A and B of the first and second rows should not be wrapped. like: 
```
┌─────┬──────────────────────┬──────────────────────┬────────────────┐
│ IDX │ A                    │ B                    │ C              │
├─────┼──────────────────────┼──────────────────────┼────────────────┤
│   1 │ abcd甲乙丙丁abcd      │ abcd甲乙丙丁abcd       │ abcd甲乙丙丁ab │
│     │                      │                      │ cd             │
│   2 │ abcdabcdabcdabcdabcd │ abcdabcdabcdabcdabcd │ abcdabcdab     │
│     │                      │                      │ cdabcdabcd     │
│     │ abcd                 │ abcd                 │ abcd           │
│   3 │ 甲乙丙丁甲乙丙丁甲乙    │ 甲乙丙丁甲乙丙丁甲乙.    │ 甲乙丙丁       │
│     │ 丙丁                 │ 丙丁                 │                │
└─────┴──────────────────────┴──────────────────────┴────────────────┘
```
**Software (please complete the following information):**
 - OS: MacOS Sequoia 15.1.1
 - GoLang Version: go1.22.5 darwin/arm64

### PR DESCRIPTION
**Pull request by jedib0t**
The `text` package Wrap* functions were not accounting for display width when wrapping a word or a sentence. This changes fixes it.

Addl. change: rename `RuneWidthWithoutEscSequences` to `StringWidthWithoutEscSequences` in a backward compatible way.

### CODE REVIEW

File: text/wrap.go [hunk 1]
```diff
@@ -111,7 +110,7 @@ func appendChar(char rune, wrapLen int, lineLen *int, inEscSeq bool, lastSeenEsc
 
 		// increment the line index if not in the middle of an escape sequence
 		if !inEscSeq {
-			*lineLen++
+			*lineLen += RuneWidth(char)
```
Comment (jedib0t) [inline text/wrap.go:113]: @L0nm4r this line was the buggy line resulting in misaligned text during wrapping.
